### ISSUE TITLE
Use Legacy SQL Boolean?

### ISSUE THREAD

**Issue by Jonovono** [tylertreat/BigQuery-Python#100]
Hi. I am wondering if there is a way I can set this to false for my queries?

For example, using this: https://cloud.google.com/bigquery/docs/reference/v2/jobs#resource-representations

they have the 'useLegacySQL' bool.

**Comment by Jonovono** [comment]
Added in a pull request #101

**Comment by tylertreat** [comment]
Addressed in #101.
