### ISSUE TITLE
Standard SQL support

### ISSUE THREAD

**Issue by ereli** [tylertreat/BigQuery-Python#147]
Looking at this it seem that this still uses legacy SQL instead of the new standard SQL
are you considering adding support for Std. SQL instead or in addition legacy SQL? https://github.com/tylertreat/BigQuery-Python/blob/96ff0b1db8bb6172714933e8fd4716ef287dc95d/bigquery/query_builder.py#L164

**Comment by tylertreat** [comment]
I don't have any plans to implement this myself at the moment, but I'm happy to accept PRs.

**Comment by ajtkulov** [comment]
actually, it supports StandardSQL: 

`def query(self, query, max_results=None, timeout=0, dry_run=False, use_legacy_sql=None, external_udf_uris=None)`

`job_id, _results = client.query('''put standard sql here''', use_legacy_sql = False)`

**Comment by tylertreat** [comment]
@ajtkulov good catch, I forgot that was added. :) https://github.com/tylertreat/BigQuery-Python/pull/101
