### ISSUE TITLE
Request had insufficient authentication scopes when creating a table

### ISSUE THREAD

**Issue by brspurri** [tylertreat/BigQuery-Python#151]
I am trying to perform a simple table create using the code:

```
client = get_client(json_key_file=key)
exists = client.check_table(dataset, tablename)
if not exists:
    created = client.create_table(dataset, tablename, schema)
    if not created:
        sys.exit('Error creating table')
```

I see the `check_table` method returning correctly, but but on `create_table`, I am getting the error response on the HTTP call.
```
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Request had insufficient authentication scopes.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```

I have created a Google IAM **service-account** with the roles `Project->Owner` *and* `BigQuery->BigQuery Admin`, and am referencing that service accounts `.json` credential files.

Does anyone know where I am gong wrong here? To me, this all looks correct, and I've been pulling my hair out for a while over this. Why would a table check call work, but a table create call be unauthorized?

**Comment by tylertreat** [comment]
Have you tried adding the `bigquery.dataOwner` role to the service account? https://cloud.google.com/iam/docs/understanding-roles#bigquery-roles

**Comment by brspurri** [comment]
Thanks for the quick response! I just tried adding the `BigQuery->DataOwner` role as well. No go. (The `BigQuery->Admin` is *suppose* to have access to all datasets too).

**Comment by tylertreat** [comment]
Hmm, let me double check my permissions...

**Comment by tylertreat** [comment]
Ok, I verified that the `DataOwner` role works, but there is an important nuance with how your client is created. You need to set `readonly=False`. By default it's set to `True`.

```python
client = get_client(json_key_file='/path/to/my/key.json', readonly=False)
```

**Comment by brspurri** [comment]
Nice! That did it. Hadn't realized the default value was `True`. Thanks!

**Comment by tylertreat** [comment]
Yeah, probably not the most user-friendly default but it was more of a security/safety-minded default. Should probably be documented better. Glad you got it working though.
