### ISSUE TITLE
Allow get_client to read key from a file

### ISSUE THREAD

**Issue by tylertreat** [tylertreat/BigQuery-Python#42]
`get_client` currently requires the private key to be passed in as a string. It would be more convenient to just pass the file name and let it handle reading it. Allow the key itself or the file name to be passed in through the `private_key` kwarg.

**Comment by tylertreat** [comment]
Fixed in e8a77965baf09b057fe950ecc44a343c39e48742.

**Comment by brspurri** [comment]
Where could I get the key file from Google? Any pointers?

**Comment by tylertreat** [comment]
@brspurri based on #151 I'm guessing you got this resolved?
