### ISSUE TITLE
I think you should add eorr handing to your framework

### ISSUE THREAD

**Issue by thinksource** [tylertreat/BigQuery-Python#47]
When I execute your framework, I think you need error handing for example:

I get error for same query:

returned "Field 'area_code' not found in table 'testdata.zip_code'; did you mean 'area_codes'?"

**Comment by thinksource** [comment]
I just want to have a way to get the error json object.

**Comment by tylertreat** [comment]
I need more information to be able to tell what's going on. This isn't enough for me to go off of.

**Comment by tylertreat** [comment]
Closing until further information/explanation is provided.
