### ISSUE TITLE
Error with your basic connection script example?

### ISSUE THREAD

**Issue by arnicas** [tylertreat/BigQuery-Python#48]
When I try to run your Basic Usage connection example, with the path to the .12 key file for "key", I get an error saying:
get_client() got an unexpected keyword argument 'private_key_file'

I think your example needs updating?

**Comment by tylertreat** [comment]
I have not cut a new release with the `get_client` changes. The latest version on pypi is 0.1.1. Since this is a breaking change, I think I will cut a 1.0.0 release. Look for that later today.

**Comment by arnicas** [comment]
Thanks!!

**Comment by tylertreat** [comment]
1.0.0 has been released (https://github.com/tylertreat/BigQuery-Python/releases/tag/v1.0.0) and is on pypi, so the readme should be consistent with this version. Let me know if you hit any issues.
