### ISSUE TITLE
Data limit?

### ISSUE THREAD

**Issue by caterpillars** [tylertreat/BigQuery-Python#49]
Hi,

It seems that there is a limit of how much data you can read? Whenever I read more data ( a fat table or a skinny long table), the reading is not successful and it only returns partial data or nothing. Is there anyway to get around this?

Thanks,

Hongli

**Comment by tylertreat** [comment]
There is a practical limit, yes, but that's a limitation of Google's API. You should be paginating your results. This library doesn't currently expose the page token, but when you submit a query, the results are saved to a temporary table. From there, you can safely paginate using the `offset` and `limit` kwargs of `get_query_rows`.

**Comment by caterpillars** [comment]
Thanks, will try that.

**Comment by tylertreat** [comment]
You might also refer to `allowLargeResults` (see https://github.com/tylertreat/BigQuery-Python/issues/50).

**Comment by caterpillars** [comment]
Thanks for the info. Will you make this keywords exposed?

**Comment by tylertreat** [comment]
Been pretty busy lately but I will try to get to it soon. Otherwise I will accept PRs if someone wants to take a crack at it sooner.

**Comment by caterpillars** [comment]
Thanks for the info.

**Comment by tylertreat** [comment]
Addressed with https://github.com/tylertreat/BigQuery-Python/pull/56.
