### ISSUE TITLE
Allow Large Results

### ISSUE THREAD

**Issue by ryan-marshall** [tylertreat/BigQuery-Python#50]
Is there currently a way to set the allowLargeResults job argument to true using this package?

**Comment by tylertreat** [comment]
It's not exposed right now, but it wouldn't be terribly difficult to add. It would probably make sense to add a `configuration` kwarg to `query`: https://github.com/tylertreat/BigQuery-Python/blob/master/bigquery/client.py#L123

PRs are accepted :)

**Comment by ryan-marshall** [comment]
good deal. thanks!

**Comment by tylertreat** [comment]
Addressed with https://github.com/tylertreat/BigQuery-Python/pull/56.
