### ISSUE TITLE
Feature Request: Export Query Results to Table

### ISSUE THREAD

**Issue by cpdean** [tylertreat/BigQuery-Python#51]
This library could become a data pipeline powerhouse if it added the hooks to flush query results to tables with batch priority.

This is something you can do from the web ui by fiddling with those options at the bottom that nobody likes to look at:

![image](https://cloud.githubusercontent.com/assets/160099/6809981/5b46cc86-d234-11e4-8767-739dcdff8477.png)

Relevant docs:

https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.query.destinationTable

potential entrypoint?

https://github.com/tylertreat/BigQuery-Python/blob/master/bigquery/client.py#L147-L152

Alternatively, maybe the service could be exposed through this library to let users construct their own query obj according to the BQ docs?

**Comment by tylertreat** [comment]
I like the idea of exposing a way for users to submit their own query objects. There are too many options on the BQ side to expose each one individually and reconstruct the query. There are a few other requests that this would solve (https://github.com/tylertreat/BigQuery-Python/issues/49 and https://github.com/tylertreat/BigQuery-Python/issues/50). Perhaps either as a kwarg or even just polymorphically (either you pass a query string and we construct the query object for you or you pass a dict containing your query object).

**Comment by cpdean** [comment]
i'm planning on working on this, should i try just refactoring the internals of `BigQueryClient.query` so that it uses a reusable function that just takes a `query_data` obj?

should that reusable guy be a semi-private `_add_job` that people can call directly if they know what they're doing, or should it be more of a first-class method?

**Comment by tylertreat** [comment]
Making it part of the public API seems reasonable as long as it's
well-documented (i.e. people know what to pass to it).

**Comment by cpdean** [comment]
I'll try adding this.  I've added the lower level query proxy in a branch on my fork. Tests pass, but I'll let you know if i'm actually able to use it for what I need by next week.

**Comment by caterpillars** [comment]
I am curious if there is any update on this. This will help me a lot because I need to use allowlargeresults argument. Thanks!

**Comment by cpdean** [comment]
I'm planning on picking this back up by next week.

see my fork if you need something asap to get to the low level client lib.

I'm planning on submitting something to review for table exports. I have a
working impl but its a little messy.

**Comment by tylertreat** [comment]
Addressed with https://github.com/tylertreat/BigQuery-Python/pull/56.
