### ISSUE TITLE
datetimes not json serializable

### ISSUE THREAD

**Issue by freyley** [tylertreat/BigQuery-Python#64]
Attempting to use push_rows with datetime fields, I get this:

*** TypeError: datetime.datetime(2015, 4, 8, 11, 53, 2, 65490, tzinfo=<UTC>) is not JSON serializable

**Comment by tylertreat** [comment]
Yes, you will need to handle converting datetimes to the suitable BigQuery form: https://cloud.google.com/bigquery/preparing-data-for-bigquery?hl=en
