### ISSUE TITLE
_get_all_tables(datasetID,cache=False) returns defaultdict(None, {})

### ISSUE THREAD

**Issue by sajeetharan** [tylertreat/BigQuery-Python#68]
Hi i am trying to retrieve all the tables under a dataset using python client. why is it returning none when there are 7 tables under the public dataset.

Here is my code:

class get_Tables:
    def GET(self,r):
          tables = []
          datasetID = web.input().dataSetID
          project_id = 'publicdata'
          service_account = '10113222700-epqo6lmkl67j6u1qafha9dlke0pmcck3@developer.gserviceaccount.com'
          key = 'Digin-d245e7da9.p12'
          client = get_client(project_id, service_account=service_account,
                            private_key_file=key, readonly=True)        
          tables = client._get_all_tables(datasetID,cache=False)
          print tables

**Comment by tylertreat** [comment]
`_get_all_tables` is not part of the public API, but to be more specific, it's used by `get_tables`. There is currently no way to list *all* tables in the way you want, but PRs are welcome.

**Comment by sajeetharan** [comment]
@tylertreat how to list all the tables with the existing one?

**Comment by tylertreat** [comment]
It's not currently possible, but I think this would need to be modified to not call `_parse_table_list_response`: https://github.com/tylertreat/BigQuery-Python/blob/master/bigquery/client.py#L940-L972
