### ISSUE TITLE
not all rows being returned

### ISSUE THREAD

**Issue by lcanali** [tylertreat/BigQuery-Python#8]
when I run the following, it returns a row_count of 9025 which is the same number of rows returned when the query is run through BigQuery's web interface.

complete, row_count = client.check_job(job_id)

I run this command next:

results = client.get_query_rows(job_id)

and len(results) returns 8374, so it appears that not all the rows are being returned in the results object.

**Comment by caterpillars** [comment]
I have the same issue and I don't think it is this reason (at least in my case). If the query pull all columns (227 columns), it only returns 1542 out of 2866 rows. But if I only select 2 columns, the row_count and len(results) are the same. It looks like it can only handle curtain amount of data? I tried to call get_query_rows twice, it doesn't seem to work.
