### ISSUE TITLE
Import deprecated method to read credentials

### ISSUE THREAD

**Issue by cosenal** [tylertreat/BigQuery-Python#85]
The following error happens with the newest version of oauth2client:
`ImportError: cannot import name SignedJwtAssertionCredentials`

See https://github.com/google/oauth2client/issues/401

**Comment by ckreutz** [comment]
Same problem here and there is a discussion and workaround here: https://github.com/google/oauth2client/issues/401

**Comment by abdhk383** [comment]
I have the same error, for the moment one work around is to replace the function of _credintails in the client function  to match the required change

**Comment by ArjenNL** [comment]
i'm new to python but would really like to use package, however I get the 'failse to import signedjwt...'  error like described above. What should I do to get it working or will there be an update via pip?

**Comment by abdhk383** [comment]
An easy way is to downgrade to

pip install oauth2client==1.5.2

if that is not possible, you have to go into client.py in _credential()
function and alter that part of the code where it uses signedjwd...

**Comment by tylertreat** [comment]
I will gladly accept a PR if someone wants to submit the patch. Otherwise, I will get to fixing this when I can.

**Comment by jasonab** [comment]
I'll give it a shot this weekend

**Comment by ArjenNL** [comment]
Thanks, much appreciated:-)

**Comment by tylertreat** [comment]
Fixed in #91.
