### ISSUE TITLE
fails to import SignedJwtAssertionCredentials with the new oauth2client package (2.0.1)

### ISSUE THREAD

**Issue by abdhk383** [tylertreat/BigQuery-Python#86]
Hi,

I had recently stumbled on the following error message:
can't import SignedJwtAssertionCredentials from oauth2client

oauth2client_2.0.1 has changed their structure in comparison to oauth2client_1.5.2

more info on https://github.com/google/oauth2client/issues/401

**Comment by tylertreat** [comment]
Closing since this is a duplicate of #85.
